# Generated by Django 4.0.6 on 2022-08-12 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
